
services:
  # ganachecli: simulated test rpc on dev environment
  ganache-cli:
    container_name: ganache-cli
    build:
      context: ./docker/ganache
    ports:
      - 8545:8545
    networks:
      - test_network

  # truffle-suite
  # volumes are used here to enable hot editing :) Nice trick!
  backend:
    container_name: backend
    build:
      context: ./docker/dev
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' localhost:8545
      interval: 5s
      timeout: 5s
      retries: 5
    # command: "cd backend && yarn install"
    tty: true
    ports:
      - 5000:5000
    # volumes:
    #   - "./backend:/backend"
    networks:
      - test_network
    links:
      - ganache-cli

networks:
  test_network:
    driver: bridge
    ipam:
      driver: default
      # config:
      #   - subnet: 10.0.0.0/24
